version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -v -t -d ./...

      - run:
          name: Build Go application
          command: go build -o myapp

      - persist_to_workspace:
          root: /workspace
          paths:
            - myapp

  test:
    docker:
      - image: golang:latest

    steps:
      - attach_workspace:
          at: /workspace

      - run:
          name: Run tests
          command: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
